---
title: "Scraping twitter"
author: "Pratik Agrawal"
date: "6 Januar 2020"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

##Setup

```{r cars}
# Install Packages
install.packages("rtweet")
install.packages("ggmap")
install.packages("igraph")
install.packages("ggraph")
install.packages("tidytext")
install.packages("ggplot2")
install.packages("dplyr")
install.packages("readr")
library(ggpubr) 
library(tidyverse)

```

#STEP 1: Getting your Twitter API access

#STEP 2: Mining Tweets
```{r}
# Open Libraries
library(rtweet)

# Speficy Authentification Token's provided in your Twitter App
create_token(
  app = "Sentiment_ndtv",
  consumer_key = "",
  consumer_secret = "",
  access_token = "",
  access_secret = ""
 
)

```


```{r}
#Searching tweets
#search for 3000 tweets using the #rstats hashtag
tweets <- search_tweets("#rstats", n = 3000, type = "recent", include_rts = TRUE,
geocode = NULL, max_id = NULL, parse = TRUE, token = NULL,
retryonratelimit = FALSE, verbose = TRUE)

```
```{r}
head(tweets)
```
```{r}
## plot frequency in 1 min intervals
ts_plot(tweets, "mins")

```
```{r}
## plot multiple time series--retweets vs non-retweets
tweets %>%
dplyr::group_by(is_retweet) %>%
ts_plot("hours")
```

```{r}
## compare account activity for some important US political figures
tmls <- get_timeline(
c("SenSchumer", "SenGillibrand", "realDonaldTrump"),
n = 3000
)
## examine all twitter activity using weekly intervals
ts_plot(tmls, "weeks")
```

```{r}
## group by screen name and plot each time series
ts_plot(dplyr::group_by(tmls, screen_name), "weeks")

```


```{r}
#Get 1000 tweets from the user BillGates
BillTweets <- get_timeline("@BillGates",n = 1000) 
head(BillTweets)
```


```{r}
#Get the most recent 3 200 tweets from cnn, BBCWorld, and foxnews. 
tmls <- get_timelines(c("cnn", "BBCWorld",
"foxnews"), n = 3200)
tmls
```


```{r}
#Search for 1 000 users with the #rstats hashtag in their profile bios.
usrs <- search_users("#rstats", n = 1000)

```
```{r}
head(usrs)
```


```{r}
#Get the 3 000 most recently favorited statuses by JK Rowling
jkr <- get_favorites("jk_rowling", n = 3000)
head(jkr)
```


```{r}
#Discover what's currently trending in San Francisco
sf <- get_trends("san francisco")
head(sf)
```


```{r}
#Lookup users
## lookup users by screen_name or user_id
users <- c("KimKardashian", "justinbieber","taylorswift13","hadleywickham","hillaryclinton", "realdonaldtrump")
famous_tweeters <- lookup_users(users)

## preview users data
head(famous_tweeters)

# extract most recent tweets data from the famous tweeters
tweets_data(famous_tweeters)
```

Rtweet Documentation: 
https://cran.r-project.org/web/packages/rtweet/rtweet.pdf 